---
title: "Gesis Data"
subtitle: ""
author: "Franziska Löw"
date: ""
output: 
  html_document:
    toc: true
    toc_float: true
    theme: "lumen"
    highlight: "tango"
    code_folding: show
    self_contained: true
---

```{r include=FALSE}
library(ggplot2)     # Static data visualization
library(dplyr)       # Data manipulation
library(RColorBrewer)
library(haven)
library(tidyr)


# Theming
quartzFonts(
  Roboto =
    c("Roboto-Light",
      "Roboto-Bold",
      "Roboto-Regular",
      "Roboto-Thin")
)

theme_set(
  theme_bw(base_family = "Roboto", base_size = 12) +
    theme(
      plot.title = element_text(size = 14,
                                margin = margin(0, 0, 4, 0, "pt")),
      plot.subtitle = element_text(size = 12),
      plot.caption = element_text(size = 6),
      plot.background   = element_rect("#fafafa", "#fafafa"),
      panel.background  = element_rect("#fafafa"),
      panel.border = element_blank()
    )
)

rm(list=ls())
col <- brewer.pal(6,"Dark2")
```

## 1. Gesis Data 
```{r caching, echo = FALSE}
gesis <- read_stata("../data/gesis.dta")
```

```{r}
var.label <- c()

for (i in 1:length(gesis)) {
  var.label[i] <- attr(gesis[[i]], "label")
}
```

```{r}
gesis <- as.tbl(gesis)
names(gesis) <- var.label
```

```{r}
df <- gesis %>% transmute(month = Erhebungsmonat,
                    year = Erhebungsjahr,
                    votingParticipation = `Wahlbeteiligung: Absicht`,
                    votingParty = `Parteienwahl: Absicht`,
                    votingPartyPast = `Wahl: Rückerinnerung`,
                    spd = `Skalometer: SPD`,
                    cdu = `Skalometer: CDU`,
                    csu = `Skalometer: CSU`,
                    fdp = `Skalometer: FDP`,
                    grüne = `Skalometer: Grüne`,
                    afd = `Skalometer: Republikaner/AfD`,
                    pds = `Skalometer: PDS`,
                    government = `Skalometer: Regierung`,
                    opposition = `Skalometer: Opposition`,
                    leftright = `Links-rechts-Kontinuum`,
                    leftwing = Linksorientierung,
                    rightwing = Rechtsorientierung,
                    euMembership = `EU-Mitgliedschaft`,
                    age = `Alter in Jahren`,
                    agerange = factor(`Alter kategorisiert`),
                    bundesland = factor(Bundesland),
                    professionalEdu = `Abgeschlossene Berufsausbildung`,
                    university = `Staatsexamen o.ä.`,
                    formation = `Angestrebter Schulabschluß`,
                    profession = Berufstätigkeit,
                    profession_group = Berufsgruppe)

```

### Age 
Generate Age range categories (same as alexa data)
```{r}
df <- df %>%
  mutate(agerange = ifelse(agerange %in% c(1,2), "18-24", agerange),
         agerange = ifelse(agerange %in% c(3,4), "25-34", agerange),
         agerange = ifelse(agerange %in% c(5,6), "35-44", agerange),
         agerange = ifelse(agerange == 7, "45-49", agerange),
         agerange = ifelse(agerange %in% c(8,9), "50-69", agerange),
         agerange = ifelse(agerange == 10, "70+", agerange)) 
```

How do preferences change over time?

```{r}
plot.df <- df %>%
  group_by(agerange, year) %>%
  summarise(spd = mean(spd, na.rm = T ),
            cdu = mean(cdu, na.rm = T),
            csu = mean(csu, na.rm = T),
            fdp = mean(fdp, na.rm = T),
            grüne = mean(grüne, na.rm = T),
            afd = mean(afd, na.rm = T),
            pds = mean(pds, na.rm = T)) %>%
  gather(party, value, spd:pds)
```

```{r fig.width=12}
plot.df %>%
  filter(year >= 2000) %>%
  filter(!is.na(agerange)) %>%
  filter(party != "afd") %>%
  ggplot(aes(year, value, color=agerange, group=agerange)) +
  geom_point() + geom_line() +
  labs(x="", y="", color="") +
  facet_wrap(~party) 
```

### Professional education
```{r fig.width=12}
plot.df <- df %>%
  group_by(professionalEdu, year) %>%
  summarise(spd = mean(spd, na.rm = T ),
            cdu = mean(cdu, na.rm = T),
            csu = mean(csu, na.rm = T),
            fdp = mean(fdp, na.rm = T),
            grüne = mean(grüne, na.rm = T),
            afd = mean(afd, na.rm = T),
            pds = mean(pds, na.rm = T)) %>%
  ungroup() %>%
  gather(party, value, spd:pds) %>%
  mutate(professionalEdu = ifelse(professionalEdu==1, "Ja", professionalEdu),
         professionalEdu = ifelse(professionalEdu==2, "Nein", professionalEdu)) %>%
    filter(!is.na(professionalEdu))

plot.df %>%
  filter(year >= 2000) %>%
  filter(party != "afd") %>%
  ggplot(aes(year, value, color=professionalEdu,
             group = professionalEdu)) +
  geom_point() + geom_line() +
  labs(x="", y="", color="", title = "Abgeschlossene Berufsausbildung") +
  facet_wrap(~party) 
```

```{r fig.width=12}
plot.df <- df %>%
  group_by(university, year) %>%
  summarise(spd = mean(spd, na.rm = T ),
            cdu = mean(cdu, na.rm = T),
            csu = mean(csu, na.rm = T),
            fdp = mean(fdp, na.rm = T),
            grüne = mean(grüne, na.rm = T),
            afd = mean(afd, na.rm = T),
            pds = mean(pds, na.rm = T)) %>%
  ungroup() %>%
  gather(party, value, spd:pds) %>%
  mutate(university = factor(ifelse(university==1, "Ja", university)),
         university = factor(ifelse(university==2, "Nein", university))) %>%
  filter(!is.na(university))

plot.df %>%
  filter(year >= 2000) %>%
  filter(party != "afd") %>%
  ggplot(aes(year, value, color=university,
             group = university)) +
  geom_point() + geom_line() +
  labs(x="", y="", color="", title = "Abgeschlossene Studium") +
  facet_wrap(~party) 
```

## 2. Alexa Data
```{r}
keeps <- c("zeit.de", "welt.de", "tagesschau.de", "stern.de", "spiegel.de", "focus.de", "bild.de")
```

How similar is this site's audience to the general internet population? --> "Relative to general internet population..."

Change relation --> "Relative to the other news websites..."

### Age

```{r}
age <- read.csv("../data/alexa/demographics/age.csv")

age <- age %>%
  select(-X) %>%
  gather(site, value, focus.de,spiegel.de:tagesspiegel.de) %>%
  filter(site %in% keeps) 
```

```{r fig.width=12}
ggplot(age, aes(age, value)) +
  geom_col(fill = col[3]) +
  #coord_flip() +
  facet_wrap(~site, ncol = 7) +
  labs(x="",y="") +
  theme(axis.text.x = element_text(angle = 90),
        axis.text.y = element_blank())
```

### Gender
```{r message=FALSE, warning=FALSE}
gender <- read.csv("../data/alexa/demographics/gender.csv")

gender <- gender %>%
  select(-X) %>%
  gather(site, value, focus.de,spiegel.de:tagesspiegel.de) %>%
  filter(site %in% keeps)
```

```{r fig.width=12}
ggplot(gender, aes(gender, value)) +
  geom_col(fill = col[3]) +
  facet_wrap(~site, ncol = 7) +
  labs(x="",y="") +
  theme(axis.text.y = element_blank())
```

### Income
```{r message=FALSE, warning=FALSE}
income <- read.csv("../data/alexa/demographics/income.csv")

income <- income %>%
  select(-X) %>%
  gather(site, value, focus.de,spiegel.de:tagesspiegel.de) %>%
  filter(site %in% keeps)
```

```{r fig.width=12}
ggplot(income, aes(income, value)) +
  geom_col(fill = col[3]) +
  facet_wrap(~site, ncol = 7) +
  labs(x="",y="") +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90))
```

### Education
```{r message=FALSE, warning=FALSE}
education <- read.csv("../data/alexa/demographics/education.csv")

education <- education %>%
  select(-X) %>%
  gather(site, value, focus.de,spiegel.de:tagesspiegel.de) %>%
  filter(site %in% keeps)
```

```{r fig.width=12}
ggplot(education, aes(education, value)) +
  geom_col(fill = col[3]) +
  facet_wrap(~site, ncol = 7) +
  labs(x="",y="") +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90))
```