---
title: "Regression"
subtitle: ""
author: "Franziska Löw"
date: ""
output: 
  html_document:
    toc: true
    toc_float: true
    theme: "lumen"
    highlight: "tango"
    code_folding: show
    self_contained: true
---

```{r include=FALSE}
library(ggplot2)     # Static data visualization
library(dplyr)       # Data manipulation
library(stringr)     # String manipulation
library(lubridate)   # Date and time manipulation
library(purrr)       # Functional programming
library(tidyr)       # Reshaping
library(magrittr)    # Advanced piping
library(pushoverr)   # Pushover notifications
library(readr)       # Importing data
library(data.table)
library(stm)
library(readxl)
library(Matrix)

library(igraph)
library(corrplot)
library(patchwork)
library(ggpmisc)
library(ggraph)
library(ggiraph)
library(tidygraph)
library(RColorBrewer) 
library(ggrepel)
library(scales)      # Scales
library(viridis)     # Viridis color scales

library(tidytext)    # Tidy text mining
library(stringdist)  # String distances
library(proxy)       # Distance measures

# Theming
quartzFonts(
  Roboto =
    c("Roboto-Light",
      "Roboto-Bold",
      "Roboto-Regular",
      "Roboto-Thin")
)

theme_set(
  theme_bw(base_family = "Roboto", base_size = 8) +
    theme(
      plot.title = element_text(size = 10,
                                margin = margin(0, 0, 4, 0, "pt")),
      plot.subtitle = element_text(size = 12),
      plot.caption = element_text(size = 6),
      panel.border = element_blank()
    )
)

rm(list=ls())
col <- brewer.pal(6,"Dark2")
```

# 1. The online news market

## Pageviews
```{r}
views1 <- read.csv("../data/alexa/Historical_Traffic_Trends__Pageviews_Percent_1.csv", comment.char="#")
views2 <- read.csv("../data/alexa/Historical_Traffic_Trends__Pageviews_Percent_2.csv", comment.char="#")

views <- left_join(views1, views2 %>% 
                     select(-Metric), by = "Date") %>%
  mutate(date = as.Date(Date, "%m/%d/%Y")) %>%
  select(- c(Metric,Date)) %>%
  gather(key="site", value="views", focus.de:tagesspiegel.de)
```

```{r}
# keeps <- c("spiegel.de", "focus.de", "zeit.de","bild.de",
#           "tagesschau.de")
#drop <- c("stern.de","sueddeutsche.de")

# reach <- reach %>%
#   mutate(date = as.Date(Date, "%m/%d/%Y")) %>%
#   select(- c(Metric,Date)) %>%
#   gather(key="site", value="reach", focus.de:n.tv.de) %>%
#  filter(!site %in% drop) 

views <- views %>%
  mutate(site = ifelse(site=="bild.de","Bild.de",site),
       site = ifelse(site=="focus.de","FOCUS ONLINE",site),
       site = ifelse(site=="spiegel.de","SPIEGEL ONLINE",site),
       site = ifelse(site=="zeit.de","ZEIT ONLINE",site),
       site = ifelse(site=="tagesschau.de","Tagesschau.de",site),
       site = ifelse(site=="zdf.de","ZDF.de",site),
       site = ifelse(site=="welt.de","DIE WELT",site),
       site = ifelse(site=="n-tv.de","n-tv.de",site),
       site = ifelse(site=="deutschlandfunk.de", "DLF", site))

keepsite <- c("Tagesschau.de", "SPIEGEL ONLINE", "ZEIT ONLINE", 
              "Bild.de", "DIE WELT", "FOCUS ONLINE", "stern.de")
```

```{r}
p1 <- views %>%
  filter(date > as.POSIXct("2017-05-31")) %>%
  ggplot(aes(date, views, color=site)) +
  geom_line() +
  geom_text(data = views[views$date==max(views$date) &
                                 views$site %in% keepsite , ],
                  aes((date+3), views, label=site), hjust=0.1,
                  size=2.5, show.legend = F, check_overlap = T) +
  scale_x_date(limits = c(as.Date("2017-05-31"),as.Date("2018-02-16")),
               breaks = date_breaks("1 month"), 
               labels=date_format("%B %y", tz="CET")) +
  theme(
      legend.position   = "right",
      legend.text       =  element_text(size=6),
      axis.text       = element_text(size = 6)
    ) +
  labs(x="", y="pageviews", color="", title = "", 
      caption = "Source: Alexa Internet, Inc. (www.alexa.com)" )

p1

ggsave(plot= p1,
filename = "../figs/reach.png", device = "png",
width = 7, height = 4,
        dpi = 600
)
```

```{r}
# calculate percentual change
views$perc_change <- (views$views - lag(views$views, n=1)) / (views$views*100)

p1 <- views %>% 
  filter(date >= as.Date("2017-09-17") &
                   date <= as.Date("2017-10-01")) %>%
  ggplot(aes(date, perc_change, color=factor(site))) +
  geom_line(show.legend = F) +
  geom_text_repel(data = views[views$date=="2017-09-24", ],
                  aes(date, perc_change, label=site),
                  size=3, show.legend = F, seed = 5) +
  #scale_color_manual(values = brewer.pal(8,"Dark2")) +
  scale_x_date(breaks = date_breaks("1 day"), labels=date_format("%d.%m.", tz="CET")) +
  labs(x="",y="% change", color="") +
  theme(
      legend.text       =  element_text(size=6),
      axis.text.y       = element_text(size = 8)
    ) 

p1

ggsave(plot= p1,
filename = "../figs/perc_change.png", device = "png",
width = 6, height = 4,
        dpi = 600
)
```

## Unique User
```{r}
unique_user <- read_excel("paper/data/ddf_Februar_2018_Angebote_Ranking_Digital.xlsx", sheet = "export")
```

```{r}
keepsite <- c("Tagesschau.de", "SPIEGEL ONLINE", "ZEIT ONLINE", 
              "BILD", "DIE WELT", "FOCUS ONLINE", "stern.de")
```

```{r fig.height=12, fig.width=8}
drop <- paste("ebay", "T Online", "WEB.DE", "chefkoch", "chip",
              "gmx", "gutefrage", "Wetter", "mobile", "immo",
              "computer","Telefonbuch","örtliche","auto","wunderweib",
              "sport", "apotheke", "giga","kicker","xing","duden",
              "bunte","upday","brigitte","meda","gala","kino","check",
              "kauf","motor","doktor","feminin","koch","TV","Urbia","1&1",
              "esse","gelbe","lecker", sep="|")

keep <- paste("focus","bild","spiegel","welt","stern","süddeutsche","faz","funke","merkur","RP Online", "Express Online", "tz.de", "Huffpost","heise","Handelsblatt","Allgemeine","Tagesspiegel", sep="|")

unique_user %>%
  filter(grepl(keep, medium, ignore.case = T)) %>%
  #dplyr::top_n(50) %>%
  ggplot(aes(reorder(medium, UniqueUser_Mio), UniqueUser_Mio)) +
  geom_col() +
  coord_flip() +
  labs(x="")
```

## Traffic source

```{r}
source1 <- read.csv("../data/alexa/Traffic_Sources_1.csv", 
                    comment.char="#", stringsAsFactors = F)
source2 <- read.csv("../data/alexa/Traffic_Sources_2.csv", 
                    comment.char="#", stringsAsFactors = F)

source <- left_join(source1, source2,
                    by=c("Date","Metric")) %>%
  select(- c(Date)) %>%
  gather(key="site", value="traffic", 
         focus.de:tagesspiegel.de)


source <- source %>%
  mutate(site = ifelse(site=="bild.de","Bild.de",site),
       site = ifelse(site=="focus.de","FOCUS ONLINE",site),
       site = ifelse(site=="spiegel.de","SPIEGEL ONLINE",site),
       site = ifelse(site=="zeit.de","ZEIT ONLINE",site),
       site = ifelse(site=="tagesschau.de","Tagesschau.de",site),
       site = ifelse(site=="zdf.de","ZDF.de",site),
       site = ifelse(site=="welt.de","DIE WELT",site),
       site = ifelse(site=="n-tv.de","n-tv.de",site))

```

```{r}
p1 <- ggplot(source, aes(site, traffic, fill=Metric,
                   label = round(traffic, digits = 2))) +
  geom_col(alpha = 0.8) +
  geom_text(size = 2, position = position_stack(vjust = 0.5)) +
  labs(x = "", y = "Percentage of total traffic", 
       caption = "Source: Alexa Internet, Inc. (www.alexa.com)") +
  theme(axis.text.x = element_text(angle = 45, size = 8 ))

p1

ggsave(plot= p1,
filename = "../figs/traffic_source.png", device = "png",
width = 6, height = 4,
        dpi = 600
)
```


## Keywords
```{r message=FALSE, warning=FALSE}
setwd("../data/alexa/keywords/")
filenames <- list.files(pattern = ".tsv$")

# create an empty list that will serve as a container to receive the incoming files
list.data<-list()
 
# create a loop to read in your data
for (i in 1:length(filenames)) {
  list.data[[i]]<-read.delim(filenames[i], comment.char="#")
}

# Create DF
keywords.df <- as.data.frame(list.data[1])

for (i in 2:length(filenames)) {
  keywords.df <- rbind(keywords.df, as.data.frame(list.data[i]))
}
```

```{r}
keepsite <- c("tagesschau.de", "spiegel.de", "zeit.de", 
              "bild.de", "welt.de", "focus.de")

keywords.df.reduced <- keywords.df %>% 
  filter(nchar(as.character(site))>1) %>% filter(site %in% keepsite)
```

```{r}
keywords.df <- keywords.df %>%
  mutate(site = as.character(site)) %>%
  mutate(site = ifelse(site=="bild.de","Bild.de",site),
       site = ifelse(site=="focus.de","FOCUS ONLINE",site),
       site = ifelse(site=="spiegel.de","SPIEGEL ONLINE",site),
       site = ifelse(site=="zeit.de","ZEIT ONLINE",site),
       site = ifelse(site=="tagesschau.de","Tagesschau.de",site),
       site = ifelse(site=="deutschlandfunk.de","DLF",site),
       site = ifelse(site=="zdf.de","ZDF.de",site),
       site = ifelse(site=="welt.de","DIE WELT",site),
       site = ifelse(site=="n-tv.de","n-tv.de",site))
```

### Search Traffic %
```{r}
p1 <- keywords.df %>%
  arrange(desc(Percent_of_traffic)) %>%
  group_by(site) %>%
  top_n(10, Percent_of_traffic) %>%
  ungroup() %>%
  ggplot(aes(reorder(term, Percent_of_traffic), 
             Percent_of_traffic, fill=site)) +
  geom_col(fill=col[1], show.legend = FALSE) +
  theme_bw(base_family = "Roboto", base_size = 7) +
  coord_flip() +
  facet_wrap(~site, scales = "free") +
  labs(x= "", y = "Search traffic %", 
       title = "",
       caption = "Source: Alexa Internet, Inc. (www.alexa.com)")

p1

ggsave(plot= p1,
filename = "../figs/search_traffic.png", device = "png",
width = 9, height = 5,
        dpi = 600
)
```

### Share of voice
```{r}
keyword1 <- c("nachrichten", "news", "bundestagswahl 2017",
            "groko", "jamaika")

keyword2 <- c("cdu","csu","spd","fdp","afd",
           "die linke","die grünen")

```

```{r}
p1 <- keywords.df %>%
  filter(term %in% keyword1) %>%
  ggplot(aes(site,
             Share_of_voice, fill=term)) +
  geom_col(fill=col[3], show.legend = F) +
  coord_flip() +
  facet_grid(~term, scales = "free") +
  labs(x= "", y = "Share of voice",
       title = ""
       )

p1

ggsave(plot= p1,
filename = "../figs/keywords1.png", device = "png",
width = 6, height = 4,
        dpi = 600
)
```

```{r}
p1 <- keywords.df %>%
  filter(term %in% keyword2) %>%
  ggplot(aes(site,
             Share_of_voice, fill=term)) +
  geom_col(fill=col[3], show.legend = F) +
  coord_flip() +
  facet_grid(~term) +
  labs(x= "", y = "Share of voice",
       caption = "
  Source: Alexa Internet, Inc. (www.alexa.com)
      ",
       title = ""
       )

p1

ggsave(plot= p1,
filename = "../figs/keywords2.png", device = "png",
width = 6, height = 4,
        dpi = 600
)
```







